enum QuestionTypeEnum {
  REPONSE_COURTE = 'REPONSE_COURTE',
  PARAGRAPHE = 'PARAGRAPHE',
  CHOIX_MULTIPLE = 'CHOIX_MULTIPLE',
  CASE_COCHER = 'CASE_COCHER',
  LISTE_DEROULANTE = 'LISTE_DEROULANTE',
  ECHELLE_LINEAIRE = 'ECHELLE_LINEAIRE',
  DATE = 'DATE',
  HEURE = 'HEURE',
  NUMERIC = 'NUMERIC'
}
